apiVersion: v1
kind: Pod
metadata:
  name: infinite-count
  namespace: kubeia
  labels:
    name: infinite-count
    app: infinite-count
    date: "03082021"
    creation_method: automated
    app_version: 0.1.0
    docker_version: 0.1.1
spec:
  containers:
    - name: infinite-count
      image: jonassteinberg1/infinite_count:0.1.1
      imagePullPolicy: IfNotPresent 
